import React, { useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const initial = { dense_top_k:50,bm25_top_k:50,sparse_top_k:50,rrf_k:60,reranker_top_k:8,score_threshold:0,context_max_tokens:6000,chunk_size:600,chunk_overlap:100 };
const metrics = [['MRR','0.842','+4.2%'],['NDCG@10','0.887','+6.1%'],['Recall@10','0.918','+3.8%'],['Faithfulness','0.956','+2.4%']];
const nav = [['Overview','⌂'],['RAG Pipeline','◇'],['Knowledge Base','▣'],['Connectors','↗'],['Evaluation','◌'],['Users & Tenants','♙'],['Security','◇'],['Deployment','⇧']];

function App(){
 const [cfg,setCfg]=useState(initial),[files,setFiles]=useState([]),[dragging,setDragging]=useState(false),[status,setStatus]=useState(''),[active,setActive]=useState('Overview');
 const inputRef=useRef(null); const api=import.meta.env.VITE_API_URL||'http://localhost:8080';
 const flash=(s)=>{setStatus(s);window.setTimeout(()=>setStatus(''),3500)};
 const addFiles=(incoming)=>{const allowed=[...incoming].filter(f=>/\.(pdf|txt|md|csv|json|docx|html?)$/i.test(f.name));const rejected=[...incoming].length-allowed.length;setFiles(p=>[...p,...allowed.filter(f=>!p.some(x=>x.name===f.name&&x.size===f.size))]);flash(`${allowed.length} file${allowed.length===1?'':'s'} added${rejected?' · '+rejected+' unsupported':''}`)};
 const update=(k,v)=>setCfg(c=>({...c,[k]:Number(v)}));
 const save=async()=>{try{const r=await fetch(`${api}/v1/config`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(cfg)});if(!r.ok)throw Error();flash('Configuration saved')}catch{flash('API unavailable — start the local stack')}};
 const upload=async()=>{if(!files.length)return;const body=new FormData();files.forEach(f=>body.append('files',f));try{const r=await fetch(`${api}/v1/documents/upload`,{method:'POST',body});if(!r.ok)throw Error();flash(`${files.length} document${files.length===1?'':'s'} queued for indexing`);setFiles([])}catch{flash('Upload endpoint unavailable — files remain queued locally')}};
 return <div className="app">
  <aside className="sidebar"><div className="logo"><span className="logoMark">S</span><div>Supersonic<strong>RAG</strong></div></div><div className="workspace"><span>WORKSPACE</span><button>Acme Research <b>⌄</b></button></div><nav>{nav.map(([name,icon])=><button key={name} className={active===name?'active':''} onClick={()=>setActive(name)}><i>{icon}</i>{name}</button>)}</nav><div className="sideBottom"><div className="statusDot"/> All systems operational<div className="user"><span>AR</span><div><b>Admin</b><small>Workspace owner</small></div><em>•••</em></div></div></aside>
  <main><header><div className="crumb">Workspace <span>/</span> {active}</div><div className="headline"><div><h1>{active==='Overview'?'Good morning. Your RAG is healthy.':active}</h1><p>{active==='Overview'?'Monitor ingestion, retrieval quality, and system health from one place.':'Manage your SupersonicRAG workspace.'}</p></div><div className="actions"><button className="ghost" onClick={()=>flash('Command palette coming soon')}>⌘ K</button><button className="primary" onClick={save}>Save changes</button></div></div></header>
   {status&&<div className="toast"><span>✓</span>{status}</div>}
   <section className="hero"><div><div className="eyebrow">KNOWLEDGE WORKSPACE</div><h2>Make your knowledge searchable.</h2><p>Upload documents, tune retrieval, and measure grounded answers without leaving the console.</p><div className="heroBtns"><button className="primary" onClick={()=>inputRef.current?.click()}>+ Add knowledge</button><button className="secondary" onClick={()=>setActive('Evaluation')}>View evaluation</button></div></div><div className="heroOrb"><span>RAG</span><small>READY</small></div></section>
   <section className="metrics">{metrics.map(([n,v,d])=><div className="metric" key={n}><div><small>{n}</small><strong>{v}</strong></div><span className="trend">↗ {d}</span></div>)}<div className="metric system"><div><small>INDEX</small><strong>12,481</strong></div><span>chunks indexed</span></div></section>
   <section className="panel knowledge"><div className="sectionHead"><div><div className="kicker">KNOWLEDGE BASE</div><h3>Upload & index</h3><p>Drop files here to update your knowledge base. We will parse, chunk, embed, and index them.</p></div><span className="badge">● Ready</span></div>
    <div className={`dropzone ${dragging?'dragging':''}`} onDragEnter={e=>{e.preventDefault();setDragging(true)}} onDragOver={e=>e.preventDefault()} onDragLeave={e=>{if(e.currentTarget===e.target)setDragging(false)}} onDrop={e=>{e.preventDefault();setDragging(false);addFiles(e.dataTransfer.files)}} onClick={()=>inputRef.current?.click()}><div className="cloud">↑</div><strong>Drop your documents here</strong><span>or <u>browse files</u> from your computer</span><small>PDF · DOCX · TXT · MD · CSV · JSON · HTML</small><input ref={inputRef} hidden type="file" multiple accept=".pdf,.docx,.txt,.md,.csv,.json,.html,.htm" onChange={e=>addFiles(e.target.files)}/></div>
    {files.length>0&&<div className="queue"><div className="queueTop"><b>{files.length} ready to index</b><button onClick={()=>setFiles([])}>Clear all</button></div>{files.map((f,i)=><div className="file" key={`${f.name}-${i}`}><span className="fileIcon">{f.name.split('.').pop().toUpperCase()}</span><div><b>{f.name}</b><small>{(f.size/1024/1024).toFixed(2)} MB · Ready</small></div><button onClick={()=>setFiles(x=>x.filter((_,j)=>j!==i))}>×</button></div>)}<button className="primary full" onClick={upload}>Upload & start indexing <span>→</span></button></div>}
   </section>
   <div className="columns"><section className="panel"><div className="sectionHead"><div><div className="kicker">RETRIEVAL</div><h3>Search quality</h3><p>Adjust ranking behavior at runtime.</p></div></div>{[['dense_top_k','Dense top-K',1,200],['bm25_top_k','BM25 top-K',1,200],['sparse_top_k','Sparse top-K',1,200],['rrf_k','RRF K',1,200],['reranker_top_k','Reranker top-K',1,50],['score_threshold','Score threshold',0,1],['context_max_tokens','Context budget',500,32000]].map(([k,l,min,max])=><label key={k}><span>{l}</span><input type="number" min={min} max={max} step={k==='score_threshold'?.01:1} value={cfg[k]} onChange={e=>update(k,e.target.value)}/></label>)}</section>
    <section className="panel"><div className="sectionHead"><div><div className="kicker">INGESTION</div><h3>Chunking strategy</h3><p>Control context granularity.</p></div></div>{[['chunk_size','Chunk size',100,4000],['chunk_overlap','Overlap',0,1000]].map(([k,l,min,max])=><label key={k}><span>{l}</span><input type="number" min={min} max={max} value={cfg[k]} onChange={e=>update(k,e.target.value)}/></label>)}<div className="switches">{['Dense retrieval','BM25 search','Reranker','Parent / child','Query rewrite','Semantic cache'].map(x=><button key={x} onClick={()=>flash(`${x} settings are managed by the runtime`)}><span>{x}</span><b>ON</b></button>)}</div></section></div>
   <section className="panel eval"><div className="sectionHead"><div><div className="kicker">EVALUATION</div><h3>Quality overview</h3><p>Last evaluation · 8,240 test cases · 3 min ago</p></div><button className="secondary" onClick={()=>flash('Evaluation job queued')}>Run evaluation →</button></div><div className="evalGrid">{[['MRR','0.842','Ranking'],['MAP@10','0.821','Precision'],['NDCG@10','0.887','Relevance'],['Faithfulness','0.956','Grounding']].map(([n,v,d])=><div key={n}><small>{d}</small><strong>{v}</strong><span>{n}</span></div>)}</div></section>
  </main></div>
}
createRoot(document.getElementById('root')).render(<App/>);
