import React, { useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const initial = { dense_top_k:50,bm25_top_k:50,sparse_top_k:50,rrf_k:60,reranker_top_k:8,score_threshold:0,context_max_tokens:6000,chunk_size:600,chunk_overlap:100 };
const nav = [['Overview','⌂'],['RAG Pipeline','◇'],['Knowledge Base','▣'],['Connectors','↗'],['Evaluation','◌'],['Users & Tenants','♙'],['Security','◇'],['Deployment','⇧']];
const allowed=/\.(pdf|txt|md|csv|json|docx|html?)$/i;
const maxFileBytes=25*1024*1024;

function App(){
 const [cfg,setCfg]=useState(initial),[files,setFiles]=useState([]),[documents,setDocuments]=useState([]),[dragging,setDragging]=useState(false),[status,setStatus]=useState(''),[active,setActive]=useState('Overview'),[busy,setBusy]=useState(false);
 const inputRef=useRef(null); const api=import.meta.env.VITE_API_URL||'http://localhost:8080';
 const flash=(s)=>{setStatus(s);window.setTimeout(()=>setStatus(''),3500)};
 const loadDocuments=async()=>{try{const r=await fetch(`${api}/v1/documents`);if(r.ok)setDocuments(await r.json())}catch{}};
 const openKnowledgeBase=()=>{setActive('Knowledge Base');window.setTimeout(()=>inputRef.current?.click(),0)};
 const addFiles=(incoming)=>{const all=[...incoming],tooLarge=all.filter(f=>f.size>maxFileBytes),supported=all.filter(f=>allowed.test(f.name)&&f.size<=maxFileBytes),rejected=all.length-supported.length;setFiles(p=>[...p,...supported.filter(f=>!p.some(x=>x.name===f.name&&x.size===f.size))]);flash(`${supported.length} file${supported.length===1?'':'s'} added${tooLarge.length?` · ${tooLarge.length} over 25 MB`:''}${rejected-tooLarge.length?` · ${rejected-tooLarge.length} unsupported`:''}`)};
 const update=(k,v)=>setCfg(c=>({...c,[k]:Number(v)}));
 const save=async()=>{try{const r=await fetch(`${api}/v1/config`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(cfg)});if(!r.ok)throw Error();flash('Configuration saved')}catch{flash('API unavailable — start the local stack')}};
 const upload=async()=>{if(!files.length||busy)return;setBusy(true);const body=new FormData();files.forEach(f=>body.append('files',f));try{const r=await fetch(`${api}/v1/documents/upload`,{method:'POST',body});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'Upload failed');setFiles([]);await loadDocuments();flash(`${data.documents?.length||files.length} document${(data.documents?.length||files.length)===1?'':'s'} uploaded and queued`)}catch(e){flash(e.message||'Upload failed — files remain queued locally')}finally{setBusy(false)}};
 const pageTitle=active==='Overview'?'Your RAG workspace':active;
 return <div className="app">
  <aside className="sidebar"><div className="logo"><span className="logoMark">S</span><div>Supersonic<strong>RAG</strong></div></div><div className="workspace"><span>WORKSPACE</span><button>Acme Research <b>⌄</b></button></div><nav>{nav.map(([name,icon])=><button key={name} className={active===name?'active':''} onClick={()=>{setActive(name);if(name==='Knowledge Base')loadDocuments()}}><i>{icon}</i>{name}</button>)}</nav><div className="sideBottom"><div className="statusDot"/> API status is shown by live requests<div className="user"><span>AR</span><div><b>Admin</b><small>Workspace owner</small></div><em>•••</em></div></div></aside>
  <main><header><div className="crumb">Workspace <span>/</span> {active}</div><div className="headline"><div><h1>{pageTitle}</h1><p>{active==='Overview'?'Upload knowledge, tune retrieval, and inspect the runtime without fake operational metrics.':`Configure ${active.toLowerCase()} for this workspace.`}</p></div><div className="actions">{['Overview','RAG Pipeline'].includes(active)&&<button className="primary" onClick={save}>Save changes</button>}</div></div></header>
   {status&&<div className="toast"><span>✓</span>{status}</div>}
   {active==='Overview'&&<>
    <section className="hero"><div><div className="eyebrow">KNOWLEDGE WORKSPACE</div><h2>Make your knowledge searchable.</h2><p>Upload documents, tune retrieval, and measure grounded answers. Runtime indexing status is reported only when the API confirms it.</p><div className="heroBtns"><button className="primary" onClick={openKnowledgeBase}>+ Add knowledge</button><button className="secondary" onClick={()=>setActive('Evaluation')}>View evaluation</button></div></div><div className="heroOrb"><span>RAG</span><small>LOCAL</small></div></section>
    <section className="metrics"><div className="metric"><div><small>API</small><strong>Endpoint</strong></div><span>configured locally</span></div><div className="metric"><div><small>UPLOAD LIMIT</small><strong>25 MB</strong></div><span>per document</span></div><div className="metric"><div><small>SUPPORTED</small><strong>8 types</strong></div><span>PDF · DOCX · TXT · MD…</span></div><div className="metric system"><div><small>INDEXING</small><strong>Pending</strong></div><span>worker not connected</span></div></section>
   </>}
   {active==='Knowledge Base'&&<KnowledgeBase files={files} setFiles={setFiles} documents={documents} dragging={dragging} setDragging={setDragging} inputRef={inputRef} addFiles={addFiles} upload={upload} busy={busy}/>} 
   {active==='RAG Pipeline'&&<Pipeline cfg={cfg} update={update}/>} 
   {active==='Evaluation'&&<section className="panel eval"><div className="sectionHead"><div><div className="kicker">EVALUATION</div><h3>Evaluation workspace</h3><p>Evaluation execution is not connected yet, so no fabricated scores are shown.</p></div><button className="secondary" onClick={()=>flash('Evaluation worker is not connected yet')}>Run evaluation →</button></div><div className="emptyState">Connect the evaluation runner to populate MRR, MAP, NDCG, faithfulness, citation accuracy, latency, and cost.</div></section>}
   {['Connectors','Users & Tenants','Security','Deployment'].includes(active)&&<section className="panel emptyPage"><div className="kicker">{active.toUpperCase()}</div><h3>{active}</h3><p>This control surface is scaffolded but not connected to a backend service yet.</p><span className="badge">Not configured</span></section>}
  </main></div>
}

function KnowledgeBase({files,setFiles,documents,dragging,setDragging,inputRef,addFiles,upload,busy}){return <section className="panel knowledge"><div className="sectionHead"><div><div className="kicker">KNOWLEDGE BASE</div><h3>Upload documents</h3><p>Files are validated and stored locally. The indexing worker is not connected yet.</p></div><span className="badge">Local storage</span></div><div className={`dropzone ${dragging?'dragging':''}`} onDragEnter={e=>{e.preventDefault();setDragging(true)}} onDragOver={e=>e.preventDefault()} onDragLeave={e=>{if(e.currentTarget===e.target)setDragging(false)}} onDrop={e=>{e.preventDefault();setDragging(false);addFiles(e.dataTransfer.files)}} onClick={()=>inputRef.current?.click()}><div className="cloud">↑</div><strong>Drop your documents here</strong><span>or <u>browse files</u> from your computer</span><small>PDF · DOCX · TXT · MD · CSV · JSON · HTML · HTM · max 25 MB/file</small><input ref={inputRef} hidden type="file" multiple accept=".pdf,.docx,.txt,.md,.csv,.json,.html,.htm" onChange={e=>addFiles(e.target.files)}/></div>{files.length>0&&<div className="queue"><div className="queueTop"><b>{files.length} ready to upload</b><button onClick={()=>setFiles([])}>Clear all</button></div>{files.map((f,i)=><div className="file" key={`${f.name}-${i}`}><span className="fileIcon">{f.name.split('.').pop().toUpperCase()}</span><div><b>{f.name}</b><small>{(f.size/1024/1024).toFixed(2)} MB · Ready</small></div><button onClick={()=>setFiles(x=>x.filter((_,j)=>j!==i))}>×</button></div>)}<button className="primary full" disabled={busy} onClick={upload}>{busy?'Uploading…':'Upload documents'} <span>→</span></button></div>}{documents.length>0&&<div className="stored"><div className="queueTop"><b>Stored documents</b><span>{documents.length}</span></div>{documents.map(d=><div className="file" key={d.id}><span className="fileIcon">{d.extension.toUpperCase()}</span><div><b>{d.name}</b><small>{(d.size_bytes/1024/1024).toFixed(2)} MB · {d.status}</small></div></div>)}</div>}</section>}
function Pipeline({cfg,update}){return <><div className="columns"><section className="panel"><div className="sectionHead"><div><div className="kicker">RETRIEVAL</div><h3>Search quality</h3><p>Adjust ranking behavior at runtime.</p></div></div>{[['dense_top_k','Dense top-K',1,200],['bm25_top_k','BM25 top-K',1,200],['sparse_top_k','Sparse top-K',1,200],['rrf_k','RRF K',1,200],['reranker_top_k','Reranker top-K',1,50],['score_threshold','Score threshold',0,1],['context_max_tokens','Context budget',500,32000]].map(([k,l,min,max])=><label key={k}><span>{l}</span><input type="number" min={min} max={max} step={k==='score_threshold'?.01:1} value={cfg[k]} onChange={e=>update(k,e.target.value)}/></label>)}</section><section className="panel"><div className="sectionHead"><div><div className="kicker">INGESTION</div><h3>Chunking strategy</h3><p>Control context granularity.</p></div></div>{[['chunk_size','Chunk size',100,4000],['chunk_overlap','Overlap',0,1000]].map(([k,l,min,max])=><label key={k}><span>{l}</span><input type="number" min={min} max={max} value={cfg[k]} onChange={e=>update(k,e.target.value)}/></label>)}</section></div></>}
createRoot(document.getElementById('root')).render(<App/>);
