FROM node:22-alpine AS build
WORKDIR /app
COPY apps/admin/package*.json ./
RUN npm ci
COPY apps/admin ./
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
